backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.home, name='search'),
    path(
        'category/<str:category_name>/',
        views.home,
        name="category"
    ),
]

news/models.py
import uuid

from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.db import models

STATUS_CHOICES = [
    ('d', 'Draft'),
    ('p', 'Published'),
    ('w', 'Withdrawn'),
]


class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(
        max_length=20,
        validators=[
            MinLengthValidator(6),
            MaxLengthValidator(20),
        ]
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class News(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    cover = models.ImageField(
        upload_to='news/covers/%Y/%m/%d/', blank=True, default='')

    category = models.ForeignKey(
        Category, on_delete=models.PROTECT)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    title = models.CharField(
        max_length=64,
        validators=[
            MinLengthValidator(6),
            MaxLengthValidator(64),
        ]
    )
    description = models.TextField(
        max_length=200,
        validators=[
            MinLengthValidator(50),
            MaxLengthValidator(200),
        ]
    )
    body = models.TextField(
        max_length=5000,
        validators=[
            MinLengthValidator(100),
            MaxLengthValidator(5000),
        ]
    )
    body_is_html = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "News"

news/views.py
from django.shortcuts import get_object_or_404, render

from .models import News


def home(request):
    news_list = News.objects.filter(status='p')
    return render(request, 'news/pages/home.html', context={
        'news_list': news_list,
    })


def news(request, id):
    news = get_object_or_404(News, id=id)
    return render(request, 'news/pages/news.html', context={
        'news': news,
        'is_detail_page': True,
    })

news/templates/news/pages/home.html
{% extends "global/base.html" %}

{% block title %} Home {% endblock title %}
{% block content %}
    <div class="main-content main-content-list container">
        {% for news in news_list %}
            {% include "news/partials/news.html" %}
            {% empty %}
                <div class="center">
                    <h1>No News Available</h1>
                </div>
        {% endfor %}
    </div>
{% endblock content %}

news/templates/news/partials/news.html
<div class="news news-list-item">
    <div class="news-cover">
        {% if not news.cover %}
            <a href="https://placeholder.com"><img src="https://via.placeholder.com/250x350"></a>
        {% else %}
            <img src="{{ news.cover.url }}" alt="Temporário">
        {% endif %}
    </div>
    <div class="news-content">
        <div class="news-content-item">
            <div class="news-title-container">
                <h2 class="news-title">{{ news.title }}</h2>
            </div>
        
            <div class="news-author">           
                <span class="news-author-item">
                    <i class="fas fa-calendar-alt">
                        {{ news.created_at|date:"d/m/Y"}}
                    </i>
                </span>
                {% if news.author is not None %}
                    <span class="news-author-item">
                        <i class="fas fa-user"></i>
                        {{ news.author.first_name }} {{ news.author.last_name }}
                    </span>
                {% endif %}
                {% if news.category is not None %}
                    <span class="news-author-item">
                        <a href={% url "news:category" news.category.name %}>
                            <i class="fas fa-layer-group"></i>
                            <span>{{ news.category.name }}</span>
                        </a>
                    </span>
                {% endif %}
            </div>
        
            <p class="news-description">{{ news.description }}</p>
        </div>
        {% if not is_detail_page %}
            <footer class="news-footer">
                <a href="">
                    <i class="fas fa-eye">
                        <span>Ver mais...</span>
                    </i>
                </a>
            </footer>
        {% endif%}
    </div>
</div>